### ISSUE TITLE
Add option to output canonical URL

### ISSUE THREAD

**Issue by saagit** [alexandrevicenzi/Flex#238] opened 2020-08-16 19:51 UTC
Canonical links are handy to tell search engines which page is canonical among various permutations of URLs (e.g. https vs. http and www subdomain or not).  If doing this is desired to be optional, a possible commit is visible [here](https://github.com/saagit/Flex/commit/4d2a9f81e69ef6614b1e7f70ecd420c51a3341df) that will output canonical links when REL_CANONICAL=True.  If it should always be done, the change can obviously be simplified.

**Comment by alexandrevicenzi** [comment] 2020-08-17 19:27
If REL_CANONICAL is from Pelican I would say we need to check it.
If not, and you want canonical URLs, there should be a setting to not break any behavior.

Also, Google is not that dumb, if you do proper redirects it won't complain. The problem is serving the same content in multiple domains, which for me sounds odd, especially because Pelican is for small blogging purposes.

I'm OK with this change as long as there's a way to enable/disable it.

**Comment by saagit** [comment] 2020-08-18 19:26
REL_CANONICAL is not from Pelican but rather just something I made up.  I'm not proud of the name so if you would like something different, I'd be happy to change it.  I believe the way I implemented it in the commit I pointed to will not change the output at all unless REL_CANONICAL is set to True in the configuration, but I'm pretty new to Jinja so perhaps there's a side effect I don't understand.

I completely agree that Google isn't that dumb.  I was just trying to follow the advice on this [page](https://support.google.com/webmasters/answer/139066?hl=en).  I probably took it too literally when they said
> Use 301 redirects to tell Googlebot that a redirected URL is a better version than a given URL. Use this only when deprecating a duplicate page.

I have my site set up so that the same content shows up in http://, https://, http://www. and https://www.  The canonical link seemed like a good way to tell the search engines that I considered https:// the canonical form.

Let me know if you would like me to go ahead and make a pull request of the commit I pointed to as is, or make a change or just silently drift away.  ;-)

Thanks much for what I consider a great template.

**Comment by alexandrevicenzi** [comment] 2020-08-19 21:08
Yes, I think that this may be useful for some.

**Comment by MaevaBrunelles** [comment] 2020-11-02 17:28
Hello,

I take the liberty of intervening in this discussion as I'm looking to use this theme for my Pelican site and I saw this issue.

I've developed a [SEO plugin for Pelican](https://github.com/pelican-plugins/seo) which generate canonical URL. I've not tested yet, but I guess that if the linked PR is merged, users which use both the SEO plugin and this theme will have twice a canonical URL in the HTML generated. 

In my opinion, the responsibility of this kind of feature should become from a plugin and not a theme, thus it will avoid to have to patch each Pelican theme. What do you think?

**Comment by saagit** [comment] 2020-11-02 17:37
For the record, I'm completely fine with whatever Alexandre decides.

**Comment by alexandrevicenzi** [comment] 2020-11-03 17:38
@MaevaBrunelles your SEO plugin misses Open Graph and Twitter card AFAIK.

This theme has been around for 5 years or more, any changes like this are breaking changes and unaccepted, that's why the Canonical option from @saagit would be configurable, one can enable or disable.

The SEO plugin does not work with this theme, it would duplicate JSON-LD, used by Google, this could easily be solved by adding a setting in the theme to disable SEO in the theme, which should be always on by default.

SEO was built in the theme, it's not great but it cannot be removed anymore, it can only be disabled to not break compatibility.

This theme is old, I don't use it anymore, there are many features, sometimes it does not make sense such features, up to you if you want to send a patch disabling SEO in the theme to allow users to use your plugin. I think that this theme is probably one of the most used, or was in the past.

@saagit if @MaevaBrunelles make the changes for SEO plugin I guess you dont need to sent the Caninal URL patch anymore, we can just tell someone to use that plugin instead.

So, here is the decision:

- Canonical URL can be added to the theme as long as it's configurable and disabled by default
- Canonical URL does not need to be added if we support SEO plugin
- SEO plugin can be used only if someone sends a patch making this theme SEO configurable and enabled by default

**Comment by alexandrevicenzi** [comment] 2020-11-03 17:42
I created #254 in case someone want's to fix it.

**Closed** 2020-12-01 18:39 UTC
